### PR TITLE
fix: remove package with service in consul

### PR DESCRIPTION
**Pull request by omelyanovich-zextras**
Enhanced the package removal process with the following commands:
1) Introduced a command to delete the service definition file for the Consul service mesh. The current removal process only deletes /etc/carbonio/user-management/ directory, leaving the service definition intact in the service mesh.

2) Included a command to restart failed systemd services. After stopping and disabling the sidecar service it still exist in the memory of systemd.

### CODE REVIEW

**Review by federicorispo — CHANGES_REQUESTED** [review]
Could you please provide a description of these changes and the reasons why they are necessary?

**Comment by omelyanovich-zextras** [comment]
> Could you please provide a description of these changes and the reasons why they are necessary?

@federicorispo description added

**Comment by federicorispo** [comment]
> > Could you please provide a description of these changes and the reasons why they are necessary?
> 
> @federicorispo description added

Thanks! However, I don´t  like your proposal for two reasons:
1. The carbonio-user-management.hcl is not deleted with the package because it is defined to be backed up in the PKGBUILD (see [line 45](https://github.com/zextras/carbonio-user-management/blob/develop/package/PKGBUILD#L45)). This setting is present in all projects and was decided by the sysadmin and the PO as a desired behaviour. This is because the hcl file could be modified by the syadmin itself. and it is considered a bad practice to delete a configuration file modified by the user. So, if we decide to remove this configuration file, this change should be applied in all projects and previously discussed in a meeting with everyone.
2. From the documentation, the `systemctl reset-failed` command: __Reset the "failed" state of the specified units, or if no unit name is passed, **reset the state of all units**.__. I don't think it's a good idea to reset all the units when a single package is removed. As before, if we decide to reset the removed unit (I don't know if it makes sense)  by specifying its name, I believe this change should be applied to all projects.

These are my opinions on this matter but I ask @M0Rf30 to intervene on these because he is more experienced.

**Comment by M0Rf30** [comment]
This is wrong on all the line.
`rm ${pkgdir}/etc....` in postrm is wrong cause it refers to ${pkgdir} in postinstall and not on an already installed file.

`systemctl reset-failed` should have a reduced scope on a unit name. Anyway why are you trying to reset the status of a failed service? I'm not convinced.

the .hcl that you're trying to remove is already part of the package (it's copied in package function). it stays there also after uninstallation because of `backup` entry.

On the service-discover overall behaviour I don't have too much knowledge, but I don't think this is the right approach

**Comment by omelyanovich-zextras** [comment]
> This is wrong on all the line. `rm ${pkgdir}/etc....` in postrm is wrong cause it refers to ${pkgdir} in postinstall and not on an already installed file.
> 
> `systemctl reset-failed` should have a reduced scope on a unit name. Anyway why are you trying to reset the status of a failed service? I'm not convinced.
> 
> the .hcl that you're trying to remove is already part of the package (it's copied in package function). it stays there also after uninstallation because of `backup` entry.
> 
> On the service-discover overall behaviour I don't have too much knowledge, but I don't think this is the right approach

fixed

**Comment by omelyanovich-zextras** [comment]
> > > Could you please provide a description of these changes and the reasons why they are necessary?
> > 
> > 
> > @federicorispo description added
> 
> Thanks! However, I don´t like your proposal for two reasons:
> 
> 1. The carbonio-user-management.hcl is not deleted with the package because it is defined to be backed up in the PKGBUILD (see [line 45](https://github.com/zextras/carbonio-user-management/blob/develop/package/PKGBUILD#L45)). This setting is present in all projects and was decided by the sysadmin and the PO as a desired behaviour. This is because the hcl file could be modified by the syadmin itself. and it is considered a bad practice to delete a configuration file modified by the user. So, if we decide to remove this configuration file, this change should be applied in all projects and previously discussed in a meeting with everyone.
> 2. From the documentation, the `systemctl reset-failed` command: **Reset the "failed" state of the specified units, or if no unit name is passed, reset the state of all units.**. I don't think it's a good idea to reset all the units when a single package is removed. As before, if we decide to reset the removed unit (I don't know if it makes sense)  by specifying its name, I believe this change should be applied to all projects.
> 
> These are my opinions on this matter but I ask @M0Rf30 to intervene on these because he is more experienced.
1) It approach will be added to all packages. Current situation that after package removing it still in the consul with unhealthy state. This is why it's mandatory to delete hcl defenition. And in memory we still have user-management.service and sidecar

2) refactor systemctl reset-failed for particular services.

**Comment by M0Rf30** [comment]
> > > > Could you please provide a description of these changes and the reasons why they are necessary?
> > > 
> > > 
> > > @federicorispo description added
> > 
> > 
> > Thanks! However, I don´t like your proposal for two reasons:
> > 
> > 1. The carbonio-user-management.hcl is not deleted with the package because it is defined to be backed up in the PKGBUILD (see [line 45](https://github.com/zextras/carbonio-user-management/blob/develop/package/PKGBUILD#L45)). This setting is present in all projects and was decided by the sysadmin and the PO as a desired behaviour. This is because the hcl file could be modified by the syadmin itself. and it is considered a bad practice to delete a configuration file modified by the user. So, if we decide to remove this configuration file, this change should be applied in all projects and previously discussed in a meeting with everyone.
> > 2. From the documentation, the `systemctl reset-failed` command: **Reset the "failed" state of the specified units, or if no unit name is passed, reset the state of all units.**. I don't think it's a good idea to reset all the units when a single package is removed. As before, if we decide to reset the removed unit (I don't know if it makes sense)  by specifying its name, I believe this change should be applied to all projects.
> > 
> > These are my opinions on this matter but I ask @M0Rf30 to intervene on these because he is more experienced.
> 
> 1. It approach will be added to all packages. Current situation that after package removing it still in the consul with unhealthy state. This is why it's mandatory to delete hcl defenition. And in memory we still have user-management.service and sidecar
> 2. refactor systemctl reset-failed for particular services.

I don't agree with this. AFAIK `systemctl daemon-reload` will trigger a reload of all the configs when the unit is already removed and this should be enough. I think that it's up to the sysadmin to reboot the machine and/or do management ops in order to eliminate "that dead unit" from `systemctl list-units` output. 

I also understand the **aesthetic** point, but I would minimize interactions with systemctl, especially if the aim is to reset a representative status of a unit. How do you feel if you install a package and it does some trickeries on your computer? Especially without your awareness?

If you're not convinced, feel free to arrange a meeting to argue about this.

**Comment by federicorispo** [comment]
Closing this pull request as no meeting was arranged

**Pull request closed without merging**
